[project]
name = "no-three-in-line"
version = "0.1.0"
description = "No three in line problem solver using Gurobi"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gurobipy>=12.0.2",
    "typer>=0.16.0",
]
